# Generated by Django 5.0.3 on 2025-04-03 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppChiffrement', '0002_remove_radiologist_profile_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Usera',
        ),
    ]
